# Generated by Django 6.0.3 on 2026-04-16 08:30

import django.db.models.deletion
import django.utils.timezone
import web.models.character
import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user/photos/default.png', upload_to=web.models.user.photo_upload_to),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=web.models.character.photo_upload_to)),
                ('profile', models.TextField(max_length=1000000)),
                ('background_image', models.ImageField(upload_to=web.models.character.background_image_upload_to)),
                ('creat_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
