# Generated by Django 6.0.3 on 2026-05-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_systemprompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompts',
            new_name='prompt',
        ),
    ]
