# Generated by Django 6.0.3 on 2026-05-31 10:36

import django.db.models.deletion
import django.utils.timezone
import web.models.knowledge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_character_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to=web.models.knowledge.document_upload_to)),
                ('file_size', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='web.knowledgedocument')),
            ],
        ),
    ]
